services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: golangg
      MYSQL_PASSWORD: toor
    ports:
      -  3306:3306
